version: '3.8'

services:
  app:
    build:
      context: .
    container_name: hackrx-app
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_HOST=qdrant
      - PYTHONUNBUFFERED=1
    depends_on:
      - qdrant
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:
